# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greet-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: greeting.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greet-service
            port:
              number: 80

